version: "3.3"

services:
  database:
    image: postgis/postgis
    restart: always
    hostname: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: flink
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: flink

  #  Zookeepers
  zookeeper:
    image: zookeeper:3.7.0
    restart: always
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      JVMFLAGS: -Xmx512m
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: "*"
    healthcheck:
      test: [ "CMD-SHELL", "echo ruok | nc -w 2 zookeeper 2181" ]
      interval: 5s
      timeout: 3s
      retries: 2
    logging:
      options:
        max-size: "512k"
        max-file: "10"

  #kafka broker
  kafka1:
    image: confluentinc/cp-kafka:6.2.0
    hostname: kafka1
    depends_on:
      - zookeeper
    ports:
      - "19092:19092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092,PLAINTEXT_HOST://localhost:19092
      KAFKA_BROKER_ID: 1
      KAFKA_BROKER_RACK: "r1"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_SCHEMA_REGISTRY_URL: "schema-registry:8081"
      KAFKA_LOG_DIRS: "/var/lib/kafka/data1_0"
      KAFKA_JMX_PORT: 9991
      KAFKA_HEAP_OPTS: -Xmx1512M -Xms1512M
    logging:
      options:
        max-size: "512k"
        max-file: "10"

  #Schema Registry
  schema-registry:
    image: confluentinc/cp-schema-registry:6.2.0
    hostname: schema-registry
    depends_on:
      - zookeeper
      - kafka1
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: "zookeeper:2181"
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8081"
    logging:
      options:
        max-size: "512k"
        max-file: "10"


  kafka-ui:
    image: provectuslabs/kafka-ui
    depends_on:
      - zookeeper
      - kafka1
      - schema-registry
    ports:
      - "19000:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka1:9092"
      KAFKA_CLUSTERS_0_ZOOKEEPER: "zookeeper:2181"
      KAFKA_CLUSTERS_0_schema-registry: "http://schema-registry:8081"
      KAFKA_CLUSTERS_0_JMXPORT: 9875
      KAFKA_CLUSTERS_0_JMXSSL: "false"
    logging:
      options:
        max-size: "512k"
        max-file: "10"